### ISSUE TITLE
Add configurable options of classes that are acceptable to use in migrations

### ISSUE THREAD

**Issue by hvenables** [the-suBLAM-executive-council/dark_finger#3]
```ruby
def down
  raise ActiveRecord::IrreversibleMigration # rubocop:disable DarkFinger/MigrationConstants
end
```

I would like to use `ActiveRecord::IrreversibleMigration` in migrations as this is stable and will not be removed however darkfinger is still giving me a warning

**Comment by professor-wang-matrix-phd** [comment]
This is done. Please to be enjoy the new versions
